// Code generated by "stringer -type=BaseType"; DO NOT EDIT.

package rio

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[TypeNone-0]
	_ = x[TypeAny-1]
	_ = x[TypeBool-2]
	_ = x[TypeFloat-3]
	_ = x[TypeInt-4]
	_ = x[TypeNever-5]
	_ = x[TypeString-6]
	_ = x[TypeVoid-7]
}

const _BaseType_name = "TypeNoneTypeAnyTypeBoolTypeFloatTypeIntTypeNeverTypeStringTypeVoid"

var _BaseType_index = [...]uint8{0, 8, 15, 23, 32, 39, 48, 58, 66}

func (i BaseType) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_BaseType_index)-1 {
		return "BaseType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _BaseType_name[_BaseType_index[idx]:_BaseType_index[idx+1]]
}
