// Code generated by "stringer -type=ParseKind"; DO NOT EDIT.

package rio

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[ParseNone-0]
	_ = x[ParseArgs-1]
	_ = x[ParseBlock-2]
	_ = x[ParseCall-3]
	_ = x[ParseCase-4]
	_ = x[ParseComment-5]
	_ = x[ParseElse-6]
	_ = x[ParseFun-7]
	_ = x[ParseInfix-8]
	_ = x[ParseJunk-9]
	_ = x[ParseModify-10]
	_ = x[ParseParam-11]
	_ = x[ParseParams-12]
	_ = x[ParsePrefix-13]
	_ = x[ParseReturn-14]
	_ = x[ParseString-15]
	_ = x[ParseSwitch-16]
	_ = x[ParseSwitchEmpty-17]
	_ = x[ParseToken-18]
	_ = x[ParseVar-19]
}

const _ParseKind_name = "ParseNoneParseArgsParseBlockParseCallParseCaseParseCommentParseElseParseFunParseInfixParseJunkParseModifyParseParamParseParamsParsePrefixParseReturnParseStringParseSwitchParseSwitchEmptyParseTokenParseVar"

var _ParseKind_index = [...]uint8{0, 9, 18, 28, 37, 46, 58, 67, 75, 85, 94, 105, 115, 126, 137, 148, 159, 170, 186, 196, 204}

func (i ParseKind) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_ParseKind_index)-1 {
		return "ParseKind(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _ParseKind_name[_ParseKind_index[idx]:_ParseKind_index[idx+1]]
}
