// Code generated by "stringer -type=BaseType"; DO NOT EDIT.

package script

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[TypeNone-0]
	_ = x[TypeBool-1]
	_ = x[TypeFloat-2]
	_ = x[TypeInt-3]
	_ = x[TypeNever-4]
	_ = x[TypeString-5]
	_ = x[TypeVoid-6]
}

const _BaseType_name = "TypeNoneTypeBoolTypeFloatTypeIntTypeNeverTypeStringTypeVoid"

var _BaseType_index = [...]uint8{0, 8, 16, 25, 32, 41, 51, 59}

func (i BaseType) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_BaseType_index)-1 {
		return "BaseType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _BaseType_name[_BaseType_index[idx]:_BaseType_index[idx+1]]
}
