// Code generated by "stringer -type=NodeKind"; DO NOT EDIT.

package script

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[NodeNone-0]
	_ = x[NodeArgs-1]
	_ = x[NodeBlock-2]
	_ = x[NodeFun-3]
	_ = x[NodeCall-4]
	_ = x[NodeParams-5]
	_ = x[NodeString-6]
	_ = x[NodeType-7]
}

const _NodeKind_name = "NodeNoneNodeArgsNodeBlockNodeFunNodeCallNodeParamsNodeStringNodeType"

var _NodeKind_index = [...]uint8{0, 8, 16, 25, 32, 40, 50, 60, 68}

func (i NodeKind) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_NodeKind_index)-1 {
		return "NodeKind(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _NodeKind_name[_NodeKind_index[idx]:_NodeKind_index[idx+1]]
}
