// Code generated by "stringer -type=ParseKind"; DO NOT EDIT.

package script

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[ParseNone-0]
	_ = x[ParseBlock-1]
	_ = x[ParseCall-2]
	_ = x[ParseFun-3]
	_ = x[ParseJunk-4]
	_ = x[ParseModify-5]
	_ = x[ParseParam-6]
	_ = x[ParseParams-7]
	_ = x[ParseString-8]
	_ = x[ParseToken-9]
}

const _ParseKind_name = "ParseNoneParseBlockParseCallParseFunParseJunkParseModifyParseParamParseParamsParseStringParseToken"

var _ParseKind_index = [...]uint8{0, 9, 19, 28, 36, 45, 56, 66, 77, 88, 98}

func (i ParseKind) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_ParseKind_index)-1 {
		return "ParseKind(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _ParseKind_name[_ParseKind_index[idx]:_ParseKind_index[idx+1]]
}
