// Code generated by "stringer -type=ParseKind"; DO NOT EDIT.

package script

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[ParseNone-0]
	_ = x[ParseArgs-1]
	_ = x[ParseBlock-2]
	_ = x[ParseCall-3]
	_ = x[ParseFun-4]
	_ = x[ParseJunk-5]
	_ = x[ParseModify-6]
	_ = x[ParseParam-7]
	_ = x[ParseParams-8]
	_ = x[ParseString-9]
	_ = x[ParseToken-10]
	_ = x[ParseVar-11]
}

const _ParseKind_name = "ParseNoneParseArgsParseBlockParseCallParseFunParseJunkParseModifyParseParamParseParamsParseStringParseTokenParseVar"

var _ParseKind_index = [...]uint8{0, 9, 18, 28, 37, 45, 54, 65, 75, 86, 97, 107, 115}

func (i ParseKind) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_ParseKind_index)-1 {
		return "ParseKind(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _ParseKind_name[_ParseKind_index[idx]:_ParseKind_index[idx+1]]
}
