// Code generated by "stringer -type=TokenKind"; DO NOT EDIT.

package script

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[TokenNone-0]
	_ = x[TokenAs-1]
	_ = x[TokenBreak-2]
	_ = x[TokenCase-3]
	_ = x[TokenChange-4]
	_ = x[TokenClass-5]
	_ = x[TokenComma-6]
	_ = x[TokenCommentOpen-7]
	_ = x[TokenCommentText-8]
	_ = x[TokenConst-9]
	_ = x[TokenContinue-10]
	_ = x[TokenElse-11]
	_ = x[TokenEnd-12]
	_ = x[TokenEq-13]
	_ = x[TokenEqEq-14]
	_ = x[TokenEnum-15]
	_ = x[TokenFor-16]
	_ = x[TokenFrom-17]
	_ = x[TokenFun-18]
	_ = x[TokenGe-19]
	_ = x[TokenGt-20]
	_ = x[TokenHSpace-21]
	_ = x[TokenId-22]
	_ = x[TokenIf-23]
	_ = x[TokenIs-24]
	_ = x[TokenImport-25]
	_ = x[TokenLe-26]
	_ = x[TokenLt-27]
	_ = x[TokenJunk-28]
	_ = x[TokenNot-29]
	_ = x[TokenNEq-30]
	_ = x[TokenPlug-31]
	_ = x[TokenPub-32]
	_ = x[TokenReturn-33]
	_ = x[TokenRoundClose-34]
	_ = x[TokenRoundOpen-35]
	_ = x[TokenStringEscape-36]
	_ = x[TokenStringText-37]
	_ = x[TokenStringClose-38]
	_ = x[TokenStringOpen-39]
	_ = x[TokenStruct-40]
	_ = x[TokenSwitch-41]
	_ = x[TokenThen-42]
	_ = x[TokenVSpace-43]
	_ = x[TokenUnion-44]
	_ = x[TokenUse-45]
	_ = x[TokenVar-46]
	_ = x[TokenVartype-47]
}

const _TokenKind_name = "TokenNoneTokenAsTokenBreakTokenCaseTokenChangeTokenClassTokenCommaTokenCommentOpenTokenCommentTextTokenConstTokenContinueTokenElseTokenEndTokenEqTokenEqEqTokenEnumTokenForTokenFromTokenFunTokenGeTokenGtTokenHSpaceTokenIdTokenIfTokenIsTokenImportTokenLeTokenLtTokenJunkTokenNotTokenNEqTokenPlugTokenPubTokenReturnTokenRoundCloseTokenRoundOpenTokenStringEscapeTokenStringTextTokenStringCloseTokenStringOpenTokenStructTokenSwitchTokenThenTokenVSpaceTokenUnionTokenUseTokenVarTokenVartype"

var _TokenKind_index = [...]uint16{0, 9, 16, 26, 35, 46, 56, 66, 82, 98, 108, 121, 130, 138, 145, 154, 163, 171, 180, 188, 195, 202, 213, 220, 227, 234, 245, 252, 259, 268, 276, 284, 293, 301, 312, 327, 341, 358, 373, 389, 404, 415, 426, 435, 446, 456, 464, 472, 484}

func (i TokenKind) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_TokenKind_index)-1 {
		return "TokenKind(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _TokenKind_name[_TokenKind_index[idx]:_TokenKind_index[idx+1]]
}
