// Code generated by "stringer -type=TokenKind"; DO NOT EDIT.

package script

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[TokenNone-0]
	_ = x[TokenAs-1]
	_ = x[TokenBreak-2]
	_ = x[TokenChange-3]
	_ = x[TokenClass-4]
	_ = x[TokenComma-5]
	_ = x[TokenComment-6]
	_ = x[TokenConst-7]
	_ = x[TokenContinue-8]
	_ = x[TokenElse-9]
	_ = x[TokenEnd-10]
	_ = x[TokenEnum-11]
	_ = x[TokenFor-12]
	_ = x[TokenFrom-13]
	_ = x[TokenFun-14]
	_ = x[TokenHSpace-15]
	_ = x[TokenId-16]
	_ = x[TokenIf-17]
	_ = x[TokenIs-18]
	_ = x[TokenImport-19]
	_ = x[TokenJunk-20]
	_ = x[TokenPlug-21]
	_ = x[TokenPub-22]
	_ = x[TokenReturn-23]
	_ = x[TokenRoundClose-24]
	_ = x[TokenRoundOpen-25]
	_ = x[TokenStringEscape-26]
	_ = x[TokenStringText-27]
	_ = x[TokenStringClose-28]
	_ = x[TokenStringOpen-29]
	_ = x[TokenStruct-30]
	_ = x[TokenSwitch-31]
	_ = x[TokenThen-32]
	_ = x[TokenVSpace-33]
	_ = x[TokenUnion-34]
	_ = x[TokenUse-35]
	_ = x[TokenVar-36]
	_ = x[TokenVartype-37]
}

const _TokenKind_name = "TokenNoneTokenAsTokenBreakTokenChangeTokenClassTokenCommaTokenCommentTokenConstTokenContinueTokenElseTokenEndTokenEnumTokenForTokenFromTokenFunTokenHSpaceTokenIdTokenIfTokenIsTokenImportTokenJunkTokenPlugTokenPubTokenReturnTokenRoundCloseTokenRoundOpenTokenStringEscapeTokenStringTextTokenStringCloseTokenStringOpenTokenStructTokenSwitchTokenThenTokenVSpaceTokenUnionTokenUseTokenVarTokenVartype"

var _TokenKind_index = [...]uint16{0, 9, 16, 26, 37, 47, 57, 69, 79, 92, 101, 109, 118, 126, 135, 143, 154, 161, 168, 175, 186, 195, 204, 212, 223, 238, 252, 269, 284, 300, 315, 326, 337, 346, 357, 367, 375, 383, 395}

func (i TokenKind) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_TokenKind_index)-1 {
		return "TokenKind(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _TokenKind_name[_TokenKind_index[idx]:_TokenKind_index[idx+1]]
}
